service: ${file(./serverless-base.yml):service}
frameworkVersion: ${file(./serverless-base.yml):frameworkVersion}
package: ${file(./serverless-base.yml):package}
functions: ${file(./serverless-base.yml):functions}

provider:
  name: ${file(./serverless-base.yml):provider.name}
  runtime: ${file(./serverless-base.yml):provider.runtime}
  memorySize: 512
  timeout: 30
  region: eu-west-1
  stage: ${env:STAGE}
  endpointType: regional
  vpc:
    securityGroupIds:
      - ${env:SECURITY_GROUP_ID}
    subnetIds:
      - ${env:APP_TIER_SUBNET_ID_1}
      - ${env:APP_TIER_SUBNET_ID_2}
      - ${env:APP_TIER_SUBNET_ID_3}

plugins:
  - serverless-esbuild
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${self:service}-${env:ENVIRONMENT}.${env:DNS_ZONE}
    basePath: ''
    endpointType: 'regional'
    createRoute53Record: true
    certificateName: ${env:DOMAIN_CERT}
  esbuild:
    target: node20
    external:
      - dd-trace
