name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release:
    needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Install
        uses: ./.github/actions/install
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
        run: yarn run semantic-release
